=== newrelic/nri-redis/tests/integration/json-schema-files/dragonfly-schema-metrics.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "properties": {
    "integration_version": {
      "minLength": 1,
      "pattern": "^\\d.\\d.\\d$",
      "type": "string"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "events": {
            "items": {
              "properties": {},
              "required": []
            },
            "type": "array"
          },
          "inventory": {
            "properties": {},
            "required": [],
            "type": "object"
          },
          "metrics": {
            "items": {
              "anyOf": [
                {
                  "properties": {
                    "cluster.connectedSlaves": {
                      "type": "number"
                    },
                    "cluster.role": {
                      "minLength": 1,
                      "type": "string"
                    },
                    "db.evictedKeysPerSecond": {
                      "type": "number"
                    },
                    "db.expiredKeysPerSecond": {
                      "type": "number"
                    },
                    "db.keyspaceHitsPerSecond": {
                      "type": "number"
                    },
                    "db.keyspaceMissesPerSecond": {
                      "type": "number"
                    },
                    "event_type": {
                      "minLength": 1,
                      "pattern": "^RedisSample$",
                      "type": "string"
                    },
                    "net.blockedClients": {
                      "type": "number"
                    },
                    "net.commandsProcessedPerSecond": {
                      "type": "number"
                    },
                    "net.connectedClients": {
                      "type": "number"
                    },
                    "net.connectionsReceivedPerSecond": {
                      "type": "number"
                    },
                    "net.inputBytesPerSecond": {
                      "type": "number"
                    },
                    "net.outputBytesPerSecond": {
                      "type": "number"
                    },
                    "net.rejectedConnectionsPerSecond": {
                      "type": "number"
                    },
                    "port": {
                      "minLength": 1,
                      "type": "string"
                    },
                    "software.uptimeMilliseconds": {
                      "type": "number"
                    },
                    "software.version": {
                      "minLength": 1,
                      "type": "string"
                    },
                    "system.maxmemoryBytes": {
                      "type": "number"
                    },
                    "system.usedCpuSysChildrenMilliseconds": {
                      "type": "number"
                    },
                    "system.usedCpuSysMilliseconds": {
                      "type": "number"
                    },
                    "system.usedCpuUserChildrenMilliseconds": {
                      "type": "number"
                    },
                    "system.usedCpuUserMilliseconds": {
                      "type": "number"
                    },
                    "system.usedMemoryBytes": {
                      "type": "number"
                    },
                    "system.usedMemoryLuaBytes": {
                      "type": "number"
                    },
                    "system.usedMemoryPeakBytes": {
                      "type": "number"
                    },
                    "system.usedMemoryRssBytes": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "cluster.connectedSlaves",
                    "cluster.role",
                    "db.evictedKeysPerSecond",
                    "db.expiredKeysPerSecond",
                    "db.keyspaceHitsPerSecond",
                    "db.keyspaceMissesPerSecond",
                    "event_type",
                    "net.blockedClients",
                    "net.commandsProcessedPerSecond",
                    "net.connectedClients",
                    "net.connectionsReceivedPerSecond",
                    "net.inputBytesPerSecond",
                    "net.outputBytesPerSecond",
                    "net.rejectedConnectionsPerSecond",
                    "port",
                    "software.uptimeMilliseconds",
                    "software.version",
                    "system.maxmemoryBytes",
                    "system.usedCpuSysChildrenMilliseconds",
                    "system.usedCpuSysMilliseconds",
                    "system.usedCpuUserChildrenMilliseconds",
                    "system.usedCpuUserMilliseconds",
                    "system.usedMemoryBytes",
                    "system.usedMemoryLuaBytes",
                    "system.usedMemoryPeakBytes",
                    "system.usedMemoryRssBytes"
                  ]
                },
                {
                  "properties": {
                    "db.avgTtlMilliseconds": {
                      "type": "number"
                    },
                    "db.expires": {
                      "type": "number"
                    },
                    "db.keys": {
                      "type": "number"
                    },
                    "db.keyspace": {
                      "type": "string"
                    },
                    "event_type": {
                      "pattern": "^RedisKeyspaceSample$",
                      "type": "string"
                    },
                    "port": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "db.avgTtlMilliseconds",
                    "db.expires",
                    "db.keys",
                    "db.keyspace",
                    "event_type",
                    "port"
                  ]
                }
              ]
            },
            "minItems": 1,
            "type": "array",
            "uniqueItems": true
          }
        },
        "required": [
          "metrics",
          "inventory",
          "events"
        ]
      }
    },
    "name": {
      "minLength": 1,
      "pattern": "^com.newrelic.redis$",
      "type": "string"
    },
    "protocol_version": {
      "minLength": 1,
      "pattern": "^3$",
      "type": "string"
    }
  },
  "required": [
    "name",
    "protocol_version",
    "integration_version",
    "data"
  ],
  "type": "object"
}

=== newrelic/nri-redis/tests/integration/json-schema-files/output.json
{
  "name": "com.newrelic.redis",
  "protocol_version": "3",
  "integration_version": "1.5.0",
  "data": [
    {
      "metrics": [
        {
          "cluster.connectedSlaves": 0,
          "cluster.role": "master",
          "db.aofLastBgrewriteStatus": "ok",
          "db.aofLastRewriteTimeMiliseconds": -1,
          "db.aofLastWriteStatus": "ok",
          "db.evictedKeysPerSecond": 0,
          "db.expiredKeysPerSecond": 0,
          "db.keyspaceHitsPerSecond": 0,
          "db.keyspaceMissesPerSecond": 0,
          "db.latestForkMilliseconds": 0,
          "db.rdbBgsaveInProgress": 0,
          "db.rdbChangesSinceLastSave": 9,
          "db.rdbLastBgsaveStatus": "ok",
          "db.rdbLastBgsaveTimeMilliseconds": -1,
          "db.rdbLastSaveTime": 1759054953,
          "db.syncFull": 0,
          "db.syncPartialErr": 0,
          "db.syncPartialOk": 0,
          "event_type": "RedisSample",
          "hostname": "redis",
          "net.blockedClients": 0,
          "net.commandsProcessedPerSecond": 0.058823529411764705,
          "net.connectedClients": 1,
          "net.connectionsReceivedPerSecond": 0.029411764705882353,
          "net.inputBytesPerSecond": 1.3529411764705883,
          "net.outputBytesPerSecond": 203.52941176470588,
          "net.pubsubChannels": 0,
          "net.pubsubPatterns": 0,
          "net.rejectedConnectionsPerSecond": 0,
          "port": "6379",
          "software.uptimeMilliseconds": 5000,
          "software.version": "7.4.5",
          "system.maxmemoryBytes": 0,
          "system.memFragmentationRatio": 13.86,
          "system.totalSystemMemoryBytes": 8217751552,
          "system.usedCpuSysChildrenMilliseconds": 0,
          "system.usedCpuSysMilliseconds": 7,
          "system.usedCpuUserChildrenMilliseconds": 0,
          "system.usedCpuUserMilliseconds": 38,
          "system.usedMemoryBytes": 1094240,
          "system.usedMemoryLuaBytes": 31744,
          "system.usedMemoryPeakBytes": 1094240,
          "system.usedMemoryRssBytes": 14602240
        },
        {
          "db.avgTtlMilliseconds": 0,
          "db.expires": 0,
          "db.keys": 1,
          "db.keyspace": "db2",
          "event_type": "RedisKeyspaceSample",
          "port": "6379"
        },
        {
          "db.avgTtlMilliseconds": 0,
          "db.expires": 0,
          "db.keys": 1,
          "db.keyspace": "db0",
          "event_type": "RedisKeyspaceSample",
          "port": "6379"
        },
        {
          "db.avgTtlMilliseconds": 0,
          "db.expires": 0,
          "db.keys": 1,
          "db.keyspace": "db1",
          "event_type": "RedisKeyspaceSample",
          "port": "6379"
        }
      ],
      "inventory": {
        "acl-pubsub-default": {
          "value": "resetchannels"
        },
        "aclfile": {
          "value": ""
        },
        "acllog-max-len": {
          "value": "128"
        },
        "active-defrag-cycle-max": {
          "value": "25"
        },
        "active-defrag-cycle-min": {
          "value": "1"
        },
        "active-defrag-ignore-bytes": {
          "value": "104857600"
        },
        "active-defrag-max-scan-fields": {
          "value": "1000"
        },
        "active-defrag-threshold-lower": {
          "value": "10"
        },
        "active-defrag-threshold-upper": {
          "value": "100"
        },
        "active-expire-effort": {
          "value": "1"
        },
        "activedefrag": {
          "value": "no"
        },
        "activerehashing": {
          "value": "yes"
        },
        "always-show-logo": {
          "value": "no"
        },
        "aof-load-truncated": {
          "value": "yes"
        },
        "aof-rewrite-cpulist": {
          "value": ""
        },
        "aof-rewrite-incremental-fsync": {
          "value": "yes"
        },
        "aof-timestamp-enabled": {
          "value": "no"
        },
        "aof-use-rdb-preamble": {
          "value": "yes"
        },
        "aof_rewrite_cpulist": {
          "value": ""
        },
        "appenddirname": {
          "value": "appendonlydir"
        },
        "appendfilename": {
          "value": "appendonly.aof"
        },
        "appendfsync": {
          "value": "everysec"
        },
        "appendonly": {
          "value": "no"
        },
        "auto-aof-rewrite-min-size": {
          "value": "67108864"
        },
        "auto-aof-rewrite-percentage": {
          "value": "100"
        },
        "bgsave-cpulist": {
          "value": ""
        },
        "bgsave_cpulist": {
          "value": ""
        },
        "bind": {
          "value": "* -::*"
        },
        "bind-source-addr": {
          "value": ""
        },
        "bio-cpulist": {
          "value": ""
        },
        "bio_cpulist": {
          "value": ""
        },
        "busy-reply-threshold": {
          "value": "5000"
        },
        "client-output-buffer-limit": {
          "normal-hard-limit": "0",
          "normal-soft-limit": "0",
          "normal-soft-seconds": "0",
          "pubsub-hard-limit": "33554432",
          "pubsub-soft-limit": "8388608",
          "pubsub-soft-seconds": "60",
          "raw-value": "normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60",
          "slave-hard-limit": "268435456",
          "slave-soft-limit": "67108864",
          "slave-soft-seconds": "60"
        },
        "client-query-buffer-limit": {
          "value": "1073741824"
        },
        "cluster-allow-pubsubshard-when-down": {
          "value": "yes"
        },
        "cluster-allow-reads-when-down": {
          "value": "no"
        },
        "cluster-allow-replica-migration": {
          "value": "yes"
        },
        "cluster-announce-bus-port": {
          "value": "0"
        },
        "cluster-announce-hostname": {
          "value": ""
        },
        "cluster-announce-human-nodename": {
          "value": ""
        },
        "cluster-announce-ip": {
          "value": ""
        },
        "cluster-announce-port": {
          "value": "0"
        },
        "cluster-announce-tls-port": {
          "value": "0"
        },
        "cluster-config-file": {
          "value": "nodes.conf"
        },
        "cluster-enabled": {
          "value": "no"
        },
        "cluster-link-sendbuf-limit": {
          "value": "0"
        },
        "cluster-migration-barrier": {
          "value": "1"
        },
        "cluster-node-timeout": {
          "value": "15000"
        },
        "cluster-port": {
          "value": "0"
        },
        "cluster-preferred-endpoint-type": {
          "value": "ip"
        },
        "cluster-replica-no-failover": {
          "value": "no"
        },
        "cluster-replica-validity-factor": {
          "value": "10"
        },
        "cluster-require-full-coverage": {
          "value": "yes"
        },
        "cluster-slave-no-failover": {
          "value": "no"
        },
        "cluster-slave-validity-factor": {
          "value": "10"
        },
        "config-file": {
          "value": ""
        },
        "crash-log-enabled": {
          "value": "yes"
        },
        "crash-memcheck-enabled": {
          "value": "yes"
        },
        "daemonize": {
          "value": "no"
        },
        "databases": {
          "value": "16"
        },
        "dbfilename": {
          "value": "dump.rdb"
        },
        "dir": {
          "value": "/data"
        },
        "disable-thp": {
          "value": "yes"
        },
        "dynamic-hz": {
          "value": "yes"
        },
        "enable-debug-command": {
          "value": "no"
        },
        "enable-module-command": {
          "value": "no"
        },
        "enable-protected-configs": {
          "value": "no"
        },
        "executable": {
          "value": "/data/redis-server"
        },
        "hash-max-listpack-entries": {
          "value": "512"
        },
        "hash-max-listpack-value": {
          "value": "64"
        },
        "hash-max-ziplist-entries": {
          "value": "512"
        },
        "hash-max-ziplist-value": {
          "value": "64"
        },
        "hide-user-data-from-log": {
          "value": "no"
        },
        "hll-sparse-max-bytes": {
          "value": "3000"
        },
        "hz": {
          "value": "10"
        },
        "ignore-warnings": {
          "value": ""
        },
        "io-threads": {
          "value": "1"
        },
        "io-threads-do-reads": {
          "value": "no"
        },
        "jemalloc-bg-thread": {
          "value": "yes"
        },
        "latency-monitor-threshold": {
          "value": "0"
        },
        "latency-tracking": {
          "value": "yes"
        },
        "latency-tracking-info-percentiles": {
          "value": "50 99 99.9"
        },
        "lazyfree-lazy-eviction": {
          "value": "no"
        },
        "lazyfree-lazy-expire": {
          "value": "no"
        },
        "lazyfree-lazy-server-del": {
          "value": "no"
        },
        "lazyfree-lazy-user-del": {
          "value": "no"
        },
        "lazyfree-lazy-user-flush": {
          "value": "no"
        },
        "lfu-decay-time": {
          "value": "1"
        },
        "lfu-log-factor": {
          "value": "10"
        },
        "list-compress-depth": {
          "value": "0"
        },
        "list-max-listpack-size": {
          "value": "-2"
        },
        "list-max-ziplist-size": {
          "value": "-2"
        },
        "locale-collate": {
          "value": ""
        },
        "logfile": {
          "value": ""
        },
        "loglevel": {
          "value": "notice"
        },
        "lua-time-limit": {
          "value": "5000"
        },
        "masterauth": {
          "value": "(omitted value)"
        },
        "masteruser": {
          "value": ""
        },
        "max-new-connections-per-cycle": {
          "value": "10"
        },
